project:
  type: website

website:
  title: "Gabriela Stockler"
  # site-url: "https://gstockler.github.io/gstockler-quarto-preview/"
  site-url: "https://gstockler.github.io/"
  navbar:
    left:
      - href: index.qmd
        # text: Home
      - href: research.qmd
        text: Research
      # - href: teaching.qmd
      #   text: Teaching
      - text: CV
        href: files/CV_2024.pdf
        target: _blank
      # - href: contact.qmd
      #   text: Contact

format:
  html:
    theme:
      - litera
    css: styles.css
    toc: false

editor: visual

